Update react-native-lightbox to react-native-lightbox-v2
FaridSafi/react-native-gifted-chat pull request #2078
Opened 2021-07-26 23:56 UTC by Eloi-Perez

Changed to an updated version of Lightbox with corrected errors.

2021-10-03 23:43 UTC, alexjou approved these changes

2022-01-11 22:25 UTC, theneekz commented
Please update package.json to use the new package too and then merge this!

2022-04-14 13:23 UTC, Johan-dutoit commented
If you're able to resolve the conflicts, then this can be merged in.

2022-04-16 08:09 UTC, Johan-dutoit requested changes
Also worth updating the example to use v2 as well.
Thanks!

2022-04-16 08:09 UTC, Johan-dutoit commented on package.json
> +    "react-native-lightbox-v2": "^0.8.8",
0.9.0 exists

2022-04-16 08:09 UTC, Johan-dutoit commented on src/MessageImage.tsx
> +// @ts-ignore
No need to ignore this, as I see it's built in typescript.

2022-04-16 08:10 UTC, Johan-dutoit commented
I've made the changes locally.  No need to worry about the patch.
Thanks for the contribution!

2022-04-16 08:10 UTC, closed without merging