fix: use messages from props instead of state
FaridSafi/react-native-gifted-chat pull request #2437
Opened 2023-08-20 10:22 UTC by preynal

it's unclear why the messages were attached to state, but there was some effect resetting them, so the chat view was empty, even if it had messages.

the message container now uses the messages from props.

2023-08-24 05:47 UTC, gajjardarshithasmukhbhai approved these changes
LGTM!!

2023-08-26 20:45 UTC, anwersolangi requested changes
LGTM!
I was facing the same issue on React Native Web on Expo, where, messages from props are appearing in console.logs, however, the state was not being updated. So, I think that this approach is good, however, if we use useCallback hook in the renderMessages function and pass messages as dependency array would make sure the re-render if any change happens in messages props.

2023-11-17 14:22 UTC, edwinvrgs commented
This seems to solve https://github.com/FaridSafi/react-native-gifted-chat/issues/2411.

2023-12-05 11:41 UTC, deemyboy commented
why is this not merged yet?

2024-08-24 06:15 UTC, closed without merging

2024-08-24 06:15 UTC, kesha-antonov commented
Fixed by https://github.com/FaridSafi/react-native-gifted-chat/pull/2493